### ISSUE TITLE
Proposal for a Pdate module

### ISSUE THREAD

**Issue by paurkedal** [dbuenzli/ptime#11] opened 2017-10-21 12:09 UTC
When dealing with time for human interfacing applications, the date precision of time has a special significance, since it can refer to a working day or waking hours.  The exact meaning mapping to a time range may depend on geographic location and context and making this exact is not always desirable.  An example may be an application deadline, where a date could mean the end of the working hours on the certain date.

My suggestion is a `Pdate` module where `t` is an abstract `int` and with an API similar to `Ptime` as far as it makes sense.  Here is my sketch of how the signature would look like (sans documentation):
```ocaml
type span

module Span : sig
  type t = span
  val v : int -> span
  val zero : span
  val of_d : int -> span option
  val to_d : span -> int
  val equal : span -> span -> bool
  val compare : span -> span -> int
  val neg : span -> span
  val add : span -> span -> span
  val sub : span -> span -> span
  val abs : span -> span
  val pp : Format.formatter -> span -> unit
  val dump : Formatter.formatter -> span -> unit
end

type t

val v : int -> t
val epoch : t
val min : t
val max : t
val of_span : span -> t option
val to_span : t -> span
val equal : t -> t -> bool
val compare : t -> t -> int
val is_earlier : t -> than: t -> bool
val is_later : t -> than: t -> bool
val add_span : t -> span -> t option
val sub_span : t -> span -> t option
val diff : t -> t -> span

type date = int * int * int

val of_date : date -> t option
val to_date : t -> date

val weekday : t -> [`Mon | `Tue | `Wed | `Thu | `Fri | `Sat | `Sun]

type error_range = int * int

val pp_rfc3339_error : Format.formatter -> rfc3339_error -> unit
val rfc3339_error_to_msg :
  ('a, [`RFC3339 of error_range * rfc3339_error]) result ->
  ('a, [> `Msg of string]) result
val of_rfc3339 :
  ?sub:bool -> ?start:int -> string ->
  (t * int, [> `RFC3339 of error_range * rfc3339_error]) result
val to_rfc3339 : t -> string
val pp_rfc3339 : unit -> Format.formatter -> t -> unit
val pp_human : unit -> Format.formatter -> t -> unit
val pp : Format.formatter -> t -> unit
val dump : Format.formatter -> t -> unit
```
If you want a PR, let me now how you prefer to share the date computations.  I can think of some options: a) Move them to `Pdate` and use `Pdate.t` in `Ptime.t`, b) move them to a private module, or c) write use `Ptime` in `Pdate`, converting to/from midnight on the fly.

If you don't want to maintain it, I could make a separate library using option c. Opinions appreciated.

**Comment by dbuenzli** [comment] 2017-10-21 12:25
> My suggestion is a Pdate module where t is an abstract int and with an API similar to Ptime as far as it makes sense

I don't understand what you are proposing here. What does this `int` represent ? 

> When dealing with time for human interfacing applications,

When dealing with time for humans you want a calendar library with calendar field arithmetic and `ptime` [is not a calendar library](https://github.com/dbuenzli/ptime/blob/c3cdd9b6e883fed8733c39a750077a7b2afb760a/src/ptime.mli#L17).

**Comment by paurkedal** [comment] 2017-10-21 13:04
> I don't understand what you are proposing here. What does this int represent ?

The number of days since 1970-01-01 (local time).

> When dealing with time for humans you want a calendar library with calendar field arithmetic and ptime is not a calendar library.

I have noticed, yes. I should maybe stick with CalendarLib, though I don't need most of the calendar computations.  I'm also reconsidering what dependencies I want for [Caqti](https://github.com/paurkedal/ocaml-caqti), since ptime is more light weight and provides the computations needed to interface with databases using a canonical representation.

**Comment by dbuenzli** [comment] 2017-10-21 13:25
> The number of days since 1970-01-01 (local time).

Ok. But the problem is that the computations on `Pdate` as you propose are too limited to be useful in practice for humans, humans want calendar field arithmetic. If that's only what you need in your particular project then you can easily do the same using `Ptime.t` values at midnight, possibly hiding the representation via the module system.

> I think my confusion about ptime not being a calendar library is that it does some of the calendar arithmetic, arguably the hard part except for leap seconds,

`Ptime.weekday` was [reluctantly](https://github.com/dbuenzli/ptime/issues/6#issuecomment-202953654) introduced, but was to help dealing with non-normalized date-time formats that require such information.

**Comment by dbuenzli** [comment] 2017-10-21 13:28
I'm closing for now but feel free to continue the discussion.

**Closed** 2017-10-21 13:28 UTC
Labels: wontfix

**Comment by paurkedal** [comment] 2017-10-21 13:36
Okay, if I understand you correctly, the declaring ptime as not a calendar library is about keeping it lean.  So it would make sense to build a full calendar library on top of ptime, using `Ptime.t` for the precise time.  For date granularity I would probably prefer an `int`, converting on the fly to `Ptime.t` with zero ns, just to keep the representation minimal.  For a real date library one would have to work with different representations internally anyway, considering YMD and business weeks. Though, I'm not so sure I want to make another calendar library, even if I can depend on `Ptime.t` for some of the logic.

**Comment by dbuenzli** [comment] 2017-10-21 13:54
> Okay, if I understand you correctly, the declaring ptime as not a calendar library is about keeping it lean.

Not only, POSIX time is a bit [weird](http://erratique.ch/software/ptime/doc/Ptime.html#basics), a calendar library would be better off using either the UTC or TAI timeline.

**Comment by paurkedal** [comment] 2017-10-22 16:45
In that case I don't think we have the ideal calendar library for OCaml.  The others that I know about are Netdate from ocamlnet and calendar, which both use the POSIX approximation to UTC.  (In Netdate it's documented, for calendar I checked by adding 1 s to 1972-06-30T22:59:59.)  In practise I think it's very few applications which need both cultural time manipulation and a precise monotonic clock.  But I agree, for a library written from scratch, it would be better to represent leap seconds, since one can still fit in arithmetic based on POSIX time spans next to physical time spans, and (interpolated) conversions to and from POSIX time to utilise the system clock and NTP.  Curiously, there was [a proposal in 2006 to stop the leap second insertion](https://www.bipm.org/cc/CCTF/Allowed/18/CCTF_09-27_note_on_UTC-ITU-R.pdf); would have made things simpler for those of us who don't depend on star navigation.
